<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async和await</title>
</head>

<body>
    <script>
        /* async函数 */
        // 函数的返回值为promise对象，promise对象的结果由async函数执行的返回值决定
        /* await表达式 */
        // await右侧的表达式一般为promise对象，但也可以是其值
        // 如果表达式是promise对象，await返回的是promise成功的值
        // 如果表达式时其他值，直接将此值作为await的返回值
        /* 注意 */
        // await必须写在async函数中，但async函数中可以没有await
        // 如果await的promise失败了，就会抛出异常，需要通过try...catch来捕获处理

        // 函数的返回值为promise对象，promise对象的结果由async函数执行的返回值决定
        // async function fn1() {
        //     // return Promise.reject(2)--
        //     throw 2
        // }
        // const result = fn1()
        //     // console.log(result) // 打印出promise对象
        // result.then(
        //     value => {
        //         console.log('onResolved', value);
        //     },
        //     reason => {
        //         console.log('onRejected', reason);
        //     }
        // )

        function fn2() {
            // return Promise.resolve(2)
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    reject(6)
                }, 1000);
            })
        }

        function fn4() {
            return 4
        }

        async function fn3() {
            try {
                const value = await fn2() // await右侧表达式为promise，得到结果promise成功的value
                    // const value = await fn4() // await右侧表达式不是promise，得到结果就是表达式的值
                console.log('value', value);
            } catch (error) {
                console.log('失败的结果', error)
            }
        }
        fn3()
    </script>
</body>

</html>